### ISSUE TITLE
Essential Compatibility

### ISSUE THREAD

**Issue by FayneAldan** [kevinthegreat1/OrganizablePlayScreens-Fabric#2]
This mod causes the Friends and Featured tabs in the [Essential mod](https://essential.gg/)'s multiplayer menu to not show up correctly.
![image](https://user-images.githubusercontent.com/1149870/194778455-b39fb910-c560-4d25-a63c-8cb92420033b.png)

**Comment by kevinthegreat1** [comment]
Thanks for reporting the issue. I will try to fix this.

**Comment by kevinthegreat1** [comment]
This is fixed in the newest release. You can get it on [GitHub](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/releases/tag/1.0.2), [Modrinth](https://modrinth.com/mod/organizable-play-screens/version/1.0.2), or [Curseforge](https://www.curseforge.com/minecraft/mc-mods/organizable-play-screens/files/4060660).
